spring:
  application:
    name: socam_be
  profiles:
    active: local

  # MySQL RDS
  datasource:
    url: jdbc:mysql://localhost:3306/socam?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
