spring:
  application:
    name: socam-BE
  profiles:
    active: local

  # MySQL RDS
  datasource:
    url: jdbc:mysql://db-instant-socam-1.c1cog6k8ae32.ap-northeast-2.rds.amazonaws.com:3306/socam?characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
    username: master
    password: socam1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect