spring:
  application:
    name: socam-BE
  profiles:
    active: local

  # MySQL RDS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-instant-socam-1.c1cog6k8ae32.ap-northeast-2.rds.amazonaws.com:3306/socam?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: master        # RDS 생성 시 입력한 마스터 계정
    password: socam1234!    # 마스터 계정 비밀번호

  jpa:
    hibernate:
      ddl-auto: update      # (개발용) 테이블 자동 생성/갱신
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true       # 콘솔에 SQL 출력 (개발 중 확인용)
    open-in-view: false      # 권장 설정 (lazy 로딩 시 메모리 누수 방지)

  # 비밀번호 재설정용 이메일 전송
  mail:
    host: smtp.gmail.com
    port: 587
    username: swcampus1127@gmail.com     # ✅ 공통 Gmail 계정
    password: srdn wyqq tfsn kuib        # ✅ Gmail 앱 비밀번호 (2단계 인증에서 발급)
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

custom:
  mail:
    naver:
      host: smtp.naver.com
      port: 465
      username: joo861127@naver.com       # ✅ 공통 Naver 계정
      password: wnehghks1!                 # ✅ Naver 비밀번호 (SMTP 허용 설정 필요)
      ssl: true

logging:
  level:
    org.springframework.security: DEBUG

clova:
  ocr:
    url: "http://clovaocr-api-kr.ncloud.com/external/v1/47261/ae54612aa498e81338684f163490fa44d13c51718067382aeedfb1180dfb0e3a"
    secret-key: "YW9DSGJwUW9mbHlBeEVickdmeENWUmtuaHBUdHdSTHM="
